apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: ""
    secretKeyRef:
      name: REDIS_HOST
      key: REDIS_HOST
  - name: redisUsername
    value: ""
    secretKeyRef:
      name: REDIS_USERNAME
      key: REDIS_USERNAME
  - name: redisPassword
    value: ""
    secretKeyRef:
      name: REDIS_PASSWORD
      key: REDIS_PASSWORD
scopes:
- dapr-srv
- mhqa-a2a-srv
auth:
  secretStore: envvar-secret-store
